- name: Main Playbook
  hosts: raspberrypi
  gather_facts: false

  tasks:
    - name: Install Nginx
      include_tasks: install_nginx.yaml

    - name: Test Nginx
      include_tasks: nginx_test.yaml

    - name: Install Node
      include_tasks: install_nodejs.yaml

    - name: Test Node
      include_tasks: nodejs_test.yaml


